version: '3.3'

services:
  ns:
    image: cznic/knot:latest
    volumes:
    - ns_storage:/storage
    - ns_rundir:/rundir
    - ./ns/config:/config
    command: knotd
    networks:
    - backend
  fns:
    build: fns
    volumes:
    - ./fns/:/fns
    ports:
    - 53:5300/udp
    networks:
    - backend
    command: python3 /fns/fns.py

networks:
  backend:

volumes:
  ns_storage:
  ns_config:
  ns_rundir:
