version: '3.3'

services:
  ns:
    image: cznic/knot:latest
    volumes:
    - ns_storage:/storage
    - ns_rundir:/rundir
    - ./ns/config:/config
    - ./addagilezone.sh:/root/bin/addagilezone.sh
    ports:
    - 5301:53/udp
    - 5301:53/tcp
    command: knotd
    networks:
    - backend
  fns:
    build: fns
    volumes:
    - ./fns/:/fns
    ports:
    - 53:5300/udp
    - 53:5300/tcp
    environment:
      ADNSSEC_UPSTREAM_HOST: ns
      ADNSSEC_UPSTREAM_PORT: 53
    networks:
    - backend
    command: python3 /fns/fns.py

networks:
  backend:

volumes:
  ns_storage:
  ns_config:
  ns_rundir:
